services:
  reelrent_db:
    image: postgres:16
    container_name: reelrent_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reelrent
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  reelrent_api:
    image: node:20-alpine
    container_name: reelrent_api
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3002:3002"
    depends_on:
      - reelrent_db
    environment:
      PORT: 3002
      DB_HOST: reelrent_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: reelrent

volumes:
  db_data:
